#version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:8501"
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ./data:/app/data
    depends_on:
      - qdrant
      - ollama
      - tika

  streamlit:
    build: .
    command: streamlit run src/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ./data:/app/data
    depends_on:
      - qdrant
      - ollama
      - tika

  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  tika:
    image: apache/tika:latest
    ports:
      - "9998:9998"