version: "3.8"
services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
    depends_on:
      - qdrant
      - ollama

  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"