# Academic Advisor RAG System Configuration
system:
  name: "Fowler School of Engineering Academic Advisor"
  version: "1.0.0"
  description: "Unified collection-based RAG system for academic advising"

# Qdrant Vector Database Configuration
qdrant:
  host: "localhost"
  port: 6333
  timeout: 150
  collections:
    major_catalogs: "major_catalogs"
    minor_catalogs: "minor_catalogs"
    general_knowledge: "general_knowledge"
    4_year_plans: "4_year_plans"

data:
  major_catalog_json_path: "data/major_catalog_json"
  minor_catalog_path: "data/minor_catalog"
  general_knowledge_path: "data/general_knowledge"
  4_year_plans: "data/4_year_plans"

# Embedding Configuration
embedding:
  # compute cluster embedding model
  model: "bge-m3:567m"
  # local laptop embedding model  
  # model: "nomic-embed-text"
  
  batch_size: 32
  ollama_host: "localhost"
  ollama_port: 11434
  add_prefixes: true
  lowercase: false
  normalize_unicode: true
  collapse_whitespace: true
  dehyphenate: true

# Chunker Configuration
chunker:
  strategy: "recursive"
  target_tokens: 1000
  min_tokens: 500
  overlap_ratio: 0.1
  respect_headings: true
 
# LLM Configuration
llm:
  # Cluster deployment with larger model
  #model: "deepseek-r1:70b"
  model: "gpt-oss:120b"
  # Local development fallback
  # model: "gemma3:4b"
  temperature: 0.2
  top_p: 0.7
  max_tokens: 6000
  context_length: 128000 # larger for deepseek
  timeout: 600  # Increased timeout for larger model
  
  ollama_options:
    keep_alive: "30m"
    num_ctx: 128000
  
  system_prompt: >
    You are an expert AI academic advisor for the Fowler School of Engineering at Chapman University.
    
    Your role is to provide accurate, helpful guidance to undergraduate students about:
    - Degree requirements and graduation planning
    - Course schedules and availability
    - Prerequisites and course sequencing
    - Academic policies and procedures
    - Program-specific information
    
    IMPORTANT GUIDELINES:
    - Use the information provided in the context from university catalogs as your primary source
    - When you have relevant context, provide specific and detailed answers based on that information
    - Be specific about course codes, credit hours, and requirements when available in the context
    - If the context contains partial information, provide what you can and note what might be missing
    - Only recommend contacting academic advisors if the context truly lacks the needed information
    - Be supportive and encouraging in your responses
    - Focus on the student's specific program and catalog year when provided
    - Trust the context provided - it comes from official university documents
    
    FORMATTING FOR CHAT INTERFACES:
    - Use numbered lists and bullet points instead of tables when possible
    - Keep formatting simple and readable for text-based chat
    - Use clear step-by-step instructions when explaining processes
    - Avoid complex markdown formatting like tables with pipes (|)
    - When listing items in categories, use section numbers for main categories and restart numbering within each section
    - For course lists, group related courses under descriptive headings with bullet points rather than continuous numbering
    
    Format your responses clearly and be thorough when you have good context to work with.

    For study abroad, as long as courses come over as upper division, they can count for our upper division courses.

    If the study abroad course isn't upper division, it can count for the course but the student will need to take another upper division class to fulfill the number of upper division courses.

    To graduate, students must take at least 42 upper division units.

    If a course is offered every semester, that means it's offered both in the fall and in the spring.

    Students may take up to 18 credits each semester.

# Retrieval Configuration
retrieval:
  initial_top_k: 20
  # after reranking
  final_top_k: 15
  enable_reranking: true 
  
  # Dynamic chunk allocation per collection type
  collection_weights:
    major_catalogs: 0.4
    minor_catalogs: 0.1
    4_year_plans: 0.35
    general_knowledge: 0.15
  
  # Minimum chunks per collection when active
  min_chunks_per_collection: 5
  max_chunks_per_collection: 20
  
  # Per-collection max limits
  collection_max_chunks:
    major_catalogs: 9
    minor_catalogs: 4
    4_year_plans: 2
    general_knowledge: 15
  
  # Total retrieval budget (will be distributed dynamically)
  total_retrieval_budget: 40
  
  k_dense: 50
  k_sparse: 50
  rrf_k: 60
  fuse_weights:
    dense: 0.7 # semantic search (nomic embed/something sexier on compute cluster)
    sparse: 0.3

# Query Router Configuration
query_router:
  # Number of previous messages to consider for context-aware routing
  last_n_messages: 5
  # Method for query routing: 'keyword', 'semantic', 'llm', or 'hybrid'
  routing_method: 'hybrid'

# Reranker Configuration
reranker:
  model: "xitao/bge-reranker-v2-m3"
  batch_size: 32
  max_candidates_for_rerank: 200
  activation: "sigmoid"
