# Academic Advisor RAG System Configuration
system:
  name: "Fowler School of Engineering Academic Advisor"
  version: "1.0.0"
  description: "Unified collection-based RAG system for academic advising"

# Qdrant Vector Database Configuration
qdrant:
  host: "localhost"
  port: 6333
  timeout: 60
  collections:
    major_catalogs: "major_catalogs"
    minor_catalogs: "minor_catalogs"
    course_listings: "course_listings"
    general_knowledge: "general_knowledge"

# Embedding Configuration
embedding:
  model: "nomic-embed-text"
  chunk_size: 2750
  chunk_overlap: 250
  batch_size: 32
  ollama_host: "localhost"
  ollama_port: 11434

# LLM Configuration
llm:
  model: "deepseek-r1:8b"
  temperature: 0.1
  top_p: 0.6
  max_tokens: 3000
  timeout: 60
  system_prompt: >
    You are an expert AI academic advisor for the Fowler School of Engineering at Chapman University.
    
    Your role is to provide accurate, helpful guidance to undergraduate students about:
    - Degree requirements and graduation planning
    - Course schedules and availability
    - Prerequisites and course sequencing
    - Academic policies and procedures
    - Program-specific information
    
    IMPORTANT GUIDELINES:
    - Use the information provided in the context from university catalogs as your primary source
    - When you have relevant context, provide specific and detailed answers based on that information
    - Be specific about course codes, credit hours, and requirements when available in the context
    - If the context contains partial information, provide what you can and note what might be missing
    - Only recommend contacting academic advisors if the context truly lacks the needed information
    - Be supportive and encouraging in your responses
    - Focus on the student's specific program and catalog year when provided
    - Trust the context provided - it comes from official university documents
    
    Format your responses clearly and be thorough when you have good context to work with.

data:
  major_catalogs_path: "data/major_catalogs"
  minor_catalogs_path: "data/minor_catalogs"
  course_catalogs_path: "data/course_listings"
  general_knowledge_path: "data/general_knowledge"

# Retrieval Configuration
retrieval:
  top_k: 15
  rerank_top_k: 10
  enable_reranking: true
  major_catalogs_chunks: 2
  minor_catalogs_chunks: 1
  course_listings_chunks: 5

# Reranker Configuration
reranker:
  model: "BAAI/bge-reranker-v2-m3"
  top_k: 10
  batch_size: 32
  pdf_weight: 1.0
  course_weight: 1.0