deepseek:
  model_name: "deepseek-r1:7b"
  temperature: 0.1
  top_p: 0.6
  max_tokens: 2000

# This section controls how documents are split into smaller chunks before being sent to the LLM.
langchain:
  chunk_size: 3000
  chunk_overlap: 300
  prompt: |
    <s> You are an AI assistant for Academic Advising at Chapman University assisting students with choosing courses as well as developing four year plans, etc. Answer the question based on the given context.
    If you don’t know the answer, say "I don't know." The major and minor catalog of varying dates corresponds to the date the student has joined the University.
    For example, if a student joined in 2020, then their course catalog would be the 2020-2021 one. </s> 

    Question: {question} 
    Context: {context} 
    Answer:

chroma:
  persist_directory: "vector_db"
  top_k: 7